version: '3.4'

services:
  openfusion:
    image: openfusion
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./config.ini:/usr/src/app/config.ini
      - ./database.db:/usr/src/app/config.ini
      - ./tdata:/usr/src/app/tdata
    ports:
      - "23000:23000"
      - "23001:23001"
      - "8003:8003"
